### ISSUE TITLE
Should support anchor text

### ISSUE THREAD

**Issue by jnothman** [sloria/sphinx-issues#1]
It should be possible to use:
```
:user:`Steven Loria <sloria>`
```
rendering as just "Steven Loria" and similar for :issue:

**Comment by sloria** [comment]
This is a valid use case. I would gladly review and merge a PR for this.

**Comment by amueller** [comment]
I'm working on it. I can not run the tests locally, though :( I get

> E       TypeError: init_values() missing 1 required positional argument: 'warn'


I'm running sphinx 1.4.1

**Comment by sloria** [comment]
This feature is now released. Thanks @amueller !
