### ISSUE TITLE
Support linking to other repos

### ISSUE THREAD

**Issue by ThiefMaster** [sloria/sphinx-issues#11]
It would be nice if you could do e.g. this:

    :issue:`user/repo#123`

For example, if you fix a bug that was caused by another library and you want to link to their issue instead of something in your own/main issue tracker.

**Comment by sloria** [comment]
That would be nice. I would certainly review/merge a PR implementing this.

**Comment by sloria** [comment]
1.2.0 supports linking to external repos.
