### ISSUE TITLE
Default to linking GH Sponsors for the `:user:` role

### ISSUE THREAD

**Issue by webknjaz** [sloria/sphinx-issues#129]
So I've been using regular `extlinks` for this (having seen the idea in the tox repo years ago). But I improved it for many of the projects I contribute to by linking the GitHub Sponsors pages of people, since this role is advertised for use in bylines. Here's some examples: https://setuptools.pypa.io/en/latest/history.html#v67-7-0 / https://yarl.aio-libs.org/en/latest/changes/#released-versions / https://yarl.aio-libs.org/en/latest/contributing/guidelines/#alright-so-how-to-add-a-news-fragment.

The primary motivation is to give credit to people who contribute / send pull requests. Then, when somebody else reads that changelog and clicks on the usernames, they are hinted to tip. 

It's also worth noting, that for the accounts that don't have GH Sponsors set up, GH itself automatically redirects to their normal profile pages, so there's always a fallback.

This is basically what I propose:
```diff
- issues_user_uri = "https://github.com/{user}"
+ issues_user_uri = "https://github.com/sponsors/{user}"
```

**Comment by sloria** [comment]
This is a great idea! I'd accept a PR updating this
