### ISSUE TITLE
cve and cwe roles override Sphinx’s built-in roles

### ISSUE THREAD

**Issue by marcelm** [sloria/sphinx-issues#162]
Sphinx 8.1.0, [released yesterday](https://www.sphinx-doc.org/en/master/changes/index.html#release-8-1-0-released-oct-10-2024), has built-in support for the `:cve:` and `:cwe:` roles, which collides with the support for these roles built into sphinx-issues (added in #44 and #122/#123).

When loading the extension, there are now these warnings:
```
WARNING: while setting up extension sphinx_issues: role 'cve' is already registered, it will be overridden [app.add_role]
WARNING: while setting up extension sphinx_issues: role 'cwe' is already registered, it will be overridden [app.add_role]
```

Sphinx’s support was added in https://github.com/sphinx-doc/sphinx/pull/11781.

I noticed this because I run `sphinx-build` with `--fail-on-warning` (turn warnings into errors).

BTW, thanks a lot for the package, I wish sphinx itself would use it for their changelog ...!

**Comment by mscheltienne** [comment]
Same issue.

**Comment by sloria** [comment]
Ah thanks for the heads up. Those roles should be removed from this package, then, with a note in the README about the official roles. PRs welcome!

**Comment by sloria** [comment]
5.0.0 drops the cve and cwe roles

**Comment by mscheltienne** [comment]
Great, thanks!

**Comment by marcelm** [comment]
Perfect, thanks so much!

> PRs welcome!

No way I could have done it so fast :smile:
