### ISSUE TITLE
sphinx-issues does not declare whether it is parallel read/write safe

### ISSUE THREAD

**Issue by jfinkels** [sloria/sphinx-issues#4]
Running `sphinx-build` with the `-j` option for parallel builds causes the following warning.

```txt
WARNING: the sphinx_issues extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
```

Here is the relevant information in the Sphinx documentation: http://www.sphinx-doc.org/en/1.5.1/extdev/#extension-metadata

**Comment by sloria** [comment]
Done! Thanks for reporting this. I'll cut a hotfix release shortly.

**Comment by jfinkels** [comment]
Cool!
