### ISSUE TITLE
Add :pr: role as alias for :issue:?

### ISSUE THREAD

**Issue by jnothman** [sloria/sphinx-issues#6]
Some contributors to scikit-learn have presumed that in the changelog `:issue:` is strictly an issue, while often we would rather reference PRs (this helps us checking that everything is covered in the changelog). Perhaps (optionally) adding a `:pr:` alias would be a good idea.

**Comment by sloria** [comment]
Sounds good to me. I would gladly review and merge a PR for this.

**Comment by sloria** [comment]
This feature is now available in 1.0.0.

**Comment by marcelm** [comment]
Thanks!
